### ISSUE TITLE
Module not found: Error: Can't resolve './wasm/webassembly_codec_wrapper.js'

### ISSUE THREAD

**Issue by raviteja83** [neuvideo/lyra-js#1]
Getting `Module not found: Error: Can't resolve './wasm/webassembly_codec_wrapper.js'` when trying to use from npm package.

**Comment by mayitayew** [comment]
Confirmed this is happening. Will take a look but let me know if you get it working in your fork, and I'll pull the fix and other improvements. 
Edit: went ahead with fix
